services:
  # Development service
  ampgate-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development

  # Production service
  ampgate-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production