# Use official Node.js Alpine image as base image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json file to the working directory
COPY package*.json ./

# Install all the dependencies
RUN npm install

# Copy the content of the local directory to the working directory
COPY . .

# expose port 5173 to tell Docker that the container listens on the specified network ports at runtime
EXPOSE 5173

# Start the app in development mode
CMD npm run dev